from typing import Optional, TypedDict


class RetrievedChunk(TypedDict):
    """One chunk returned from Qdrant, after reranking and MMR."""
    text: str
    score: float
    source: str   # e.g. "Apple_10K_2024.htm"
    page: int
    doc_id: str


class RAGState(TypedDict):
    """
    Shared state flowing through every node in the LangGraph pipeline.

    Query Analyzer → fills: query_type, sub_questions, hyde_query, data_source
    DB Lookup      → fills: sql_result           (sql / hybrid queries only)
    Retriever      → fills: chunks               (rag / hybrid queries only)
    Synthesizer    → fills: answer, sources
    Evaluator      → fills: faithfulness, relevance
    Graph          → manages: retry_count
    """

    # ── Identity ───────────────────────────────────────────────────────────────
    query_id:    str   # UUID generated by run_query — links audit log, chunks, feedback
    question:    str
    tenant_id:   str   # "apple" | "goldman" | "jpmorgan" | "demo"
    customer_id: str   # specific user within the tenant

    # ── Query Analyzer ─────────────────────────────────────────────────────────
    query_type:    str          # "sql"|"hybrid"|"numerical"|"conceptual"|"comparative"|...
    sub_questions: list[str]    # split questions for multi-entity queries
    hyde_query:    str          # hypothetical answer for embedding-based search
    data_source:   str          # "rag" | "sql" | "hybrid" — drives graph routing

    # ── DB Lookup (sql / hybrid only) ──────────────────────────────────────────
    sql_result: Optional[str]  # formatted string from transactions table

    # ── Retriever (rag / hybrid only) ──────────────────────────────────────────
    chunks: list[RetrievedChunk]

    # ── Synthesizer ────────────────────────────────────────────────────────────
    answer:  str
    sources: list[str]         # e.g. ["Apple 10-K, page 14, Chunk #2"]

    # ── Evaluator ──────────────────────────────────────────────────────────────
    faithfulness: float        # threshold 0.85
    relevance:    float        # threshold 0.80
    retry_count:  int          # managed exclusively by graph.py

    # ── Cache ──────────────────────────────────────────────────────────────────
    cached: bool        # True if this response was served from semantic cache

    # ── Error handling ─────────────────────────────────────────────────────────
    error: Optional[str]


def initial_state(
    question: str,
    tenant_id: str = "demo",
    customer_id: str = "demo_user_001",
    query_id: str = "",
) -> RAGState:
    """
    Build a blank state with only the question and tenant context set.
    Every agent fills in its own fields; defaults prevent KeyError on first access.
    """
    return RAGState(
        query_id=query_id,
        question=question,
        tenant_id=tenant_id,
        customer_id=customer_id,
        query_type="",
        sub_questions=[],
        hyde_query="",
        data_source="rag",
        sql_result=None,
        chunks=[],
        answer="",
        sources=[],
        faithfulness=0.0,
        relevance=0.0,
        retry_count=0,
        cached=False,
        error=None,
    )


if __name__ == "__main__":
    s = initial_state("What was Apple's iPhone revenue in Q3 2024?", tenant_id="apple")
    assert s["question"] == "What was Apple's iPhone revenue in Q3 2024?"
    assert s["tenant_id"] == "apple"
    assert s["customer_id"] == "demo_user_001"
    assert s["data_source"] == "rag"
    assert s["sql_result"] is None
    assert s["retry_count"] == 0
    assert s["chunks"] == []
    assert s["error"] is None
    print("state.py OK —", list(s.keys()))
